import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  const fontNeue = localFont({
    src: [
      {
        path: "../fonts/NeueHaasDisplayRoman.ttf",
        weight: "400",
        style: "light",
      },
    ],
    variable: "--font-neue",
    display: "swap",
  });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${fontNeue.variable} antialiased`}>{children}</body>
    </html>
  );
}
